# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'admob' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK', '12.11.0'
  # Pods for admob

end
