# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'admob' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'Google-Mobile-Ads-SDK', '10.6.0'
  # Pods for admob

end
