# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

def read_pod_from_file(file_path)
  File.read(file_path)
end

def common_pods
  use_frameworks!
  eval(read_pod_from_file('src/ads/config/pods.txt'))
end

target 'ads' do
  common_pods
end

target 'core' do
  common_pods
end

target 'meta' do
  common_pods
  eval(read_pod_from_file('src/mediation/meta/config/pods.txt'))
end

target 'vungle' do  
  common_pods
  eval(read_pod_from_file('src/mediation/vungle/config/pods.txt'))
end


target 'adcolony' do
  common_pods
  eval(read_pod_from_file('src/mediation/adcolony/config/pods.txt'))
end
