# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

def common_pods
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK', '10.9.0'
end

target 'ads' do
  common_pods
end

target 'core' do
  common_pods
end

target 'meta' do
  common_pods
end

target 'vungle' do
  common_pods
  pod 'GoogleMobileAdsMediationVungle', '6.12.3'
end


target 'adcolony' do
  common_pods
  pod 'GoogleMobileAdsMediationAdColony', '4.9.0.2'
end
